accent = "#e75a50"
cursor = "#C0AF7F"
foreground = "#efebdc"
background = "#1B1B1B"
selection_foreground = "#1B1B1B"
selection_background = "#e75a50"

color0 = "#1B1B1B"
color1 = "#F44336"
color2 = "#a99b7a"
color3 = "#E1CE98"
color4 = "#9ba2a6"
color5 = "#9683a1"
color6 = "#77868a"
color7 = "#efebdc"
color8 = "#817f68"
color9 = "#e75a50"
color10 = "#b8ab8c"
color11 = "#F0E2B8"
color12 = "#b3bbbf"
color13 = "#ad9ab8"
color14 = "#8a9a9e"
color15 = "#f4f2e8"
