background = #1B1B1B
foreground = #efebdc
cursor-color = #C0AF7F
selection-background = #e75a50
selection-foreground = #1B1B1B

palette = 0=#1B1B1B
palette = 1=#F44336
palette = 2=#a99b7a
palette = 3=#E1CE98
palette = 4=#9ba2a6
palette = 5=#9683a1
palette = 6=#77868a
palette = 7=#efebdc
palette = 8=#817f68
palette = 9=#e75a50
palette = 10=#b8ab8c
palette = 11=#F0E2B8
palette = 12=#b3bbbf
palette = 13=#ad9ab8
palette = 14=#8a9a9e
palette = 15=#f4f2e8
