source = ~/.config/omarchy/current/theme/hyprlock.conf

general {
    ignore_empty_input = true
    fractional_scaling = 1
    hide_cursor = true  
    fail_timeout = 50
}

background {
    monitor =
    color = $color
    path = ~/.config/omarchy/current/background
    blur_passes = 1
    brightness = 0.66
    noise = 0.1
    vibrancy = -0.55
}

animations {
    enabled = true
}

label {
    monitor = eDP-1

    position = 0, -505
    halign = center
    valign = center

    font_family = "Liberation Mono"
    font_size = 14
    text =  <span>$TIME</span>
    color = rgba(195, 195, 195, 0.6)
}

label {
    monitor = eDP-1

    position = 0, -530
    halign = center
    valign = center

    font_family = "Liberation Mono"
    font_size = 14
    text = cmd[update:1000] echo $(date +"%A, %B %d")
    #text =  <span>$TIME</span>
    color = rgba(195, 195, 195, 0.6)
}

input-field {
    monitor =
    size = 300, 30

    position = 0, -565
    halign = center
    valign = center

    inner_color = rgba(125,125,125,0.0)
    outer_color = rgba(125,125,125,0.85)
    outline_thickness = 1

    font_family = JetBrainsMono Nerd Font
    font_color = $font_color

    check_color = $check_color
    placeholder_text = 
    fail_text = <i>incorrect</i>

    rounding = 1
    shadow_passes = 0
    fade_on_empty = false
    fade_timeout = 100
}


auth {
    fingerprint:enabled = true
}

animation = fadeIn, 1, 10, default, fade
animation = fadeIn, 1, 10, default, fade
animation = inputFieldDots, 1, 5, default, fade
