source = ~/.config/omarchy/current/theme/hyprlock.conf

general {
    ignore_empty_input = true
    fractional_scaling = 1
    hide_cursor = true  
    fail_timeout = 200
}

background {
    monitor =
    color = $color
    path = ~/.config/omarchy/current/background
    blur_passes = 2
    brightness = 0.5
    noise = 0
    vibrancy = -0.1
}

animations {
    enabled = true
}


label {
    monitor =

    position = 0, -290
    halign = center
    valign = center

    font_family = "JetBrainsMono Nerd Font"
    font_size = 32
    text =  <span>$TIME</span>
    color = rgba(195, 195, 195, 0.8)
}

input-field {
    monitor =
    size = 300, 50

    position = 0, -350
    halign = center
    valign = center

    inner_color = rgba(125,125,125,0.0)
    outer_color = rgba(125,125,125,0.85)
    outline_thickness = 4

    font_family = JetBrainsMono Nerd Font
    font_color = $font_color

    check_color = $check_color
    placeholder_text = 
    fail_text = <i>incorrect</i>

    rounding = 3
    shadow_passes = 0
    fade_on_empty = false
    fade_timeout = 300
}


auth {
    fingerprint:enabled = true
}

animation = fadeIn, 1, 10, default, fade
animation = fadeIn, 1, 10, default, fade
animation = inputFieldDots, 1, 5, default, fade