general.import = ["~/.config/omarchy/current/theme/alacritty.toml"]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "JetBrainsMonoNerdFont" }
bold = { family = "JetBrainsMonoNerdFont" }
italic = { family = "JetBrainsMonoNerdFont" }
size = 10

[window]
padding.x = 0
padding.y = 0
decorations = "None"
opacity = 0.1
blur = true
dynamic_padding = true

[keyboard]
bindings = [
  { key = "Insert", mods = "Shift", action = "Paste" },
  { key = "Insert", mods = "Control", action = "Copy" },
]

[cursor]
style = { shape = "Beam", blinking = "On" }
thickness = 0.1
blink_interval = 300


