#!/usr/bin/env bash
# Record the exact commit each locally-built / locally-modified repo sits on,
# so a rebuild lands on the same source rather than "whatever upstream HEAD is
# today". Writes packages/build-provenance.txt. Re-run after any build or pull.
set -euo pipefail

DOTS="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$DOTS/packages/build-provenance.txt"

# repo path : label : why it matters
REPOS="
$HOME/repos/walker|walker|source-patched, installed to /usr/local/bin/walker
$HOME/.local/share/omarchy|omarchy|6 uncommitted local modifications
$HOME/repos/Hyprlain|Hyprlain|SDDM theme written to by ~/.local/bin/sddm-bg-sync
"

{
    echo "# build provenance - generated by packages/record-provenance.sh"
    echo "# regenerate after any build, checkout or pull"
    echo

    printf '%s\n' "$REPOS" | while IFS='|' read -r path label why; do
        [ -z "${path:-}" ] && continue
        echo "[$label]"
        if [ ! -d "$path/.git" ]; then
            echo "  MISSING: $path is not a git repo on this machine"
            echo
            continue
        fi
        echo "  why:          $why"
        echo "  path:         ${path/#$HOME/~}"
        echo "  remote:       $(git -C "$path" remote get-url origin 2>/dev/null || echo '(none)')"
        echo "  branch:       $(git -C "$path" branch --show-current 2>/dev/null || echo '(detached)')"
        echo "  HEAD:         $(git -C "$path" rev-parse HEAD)"
        desc=$(git -C "$path" describe --tags --always 2>/dev/null || true)
        [ -n "$desc" ] && echo "  describe:     $desc"
        echo "  HEAD date:    $(git -C "$path" log -1 --format=%ci)"
        echo "  HEAD subject: $(git -C "$path" log -1 --format=%s)"
        dirty=$(git -C "$path" status --porcelain | wc -l)
        echo "  uncommitted:  $dirty file(s)"
        if [ "$dirty" -gt 0 ]; then
            git -C "$path" status --porcelain | sed 's/^/                /'
        fi
        # upstream tracking, so you can tell a local commit from a pushed one
        up=$(git -C "$path" rev-parse --abbrev-ref --symbolic-full-name '@{upstream}' 2>/dev/null || true)
        if [ -n "$up" ]; then
            echo "  upstream:     $up ($(git -C "$path" rev-list --left-right --count "@{upstream}...HEAD" | awk '{print $2" ahead, "$1" behind"}'))"
        else
            echo "  upstream:     none - this branch exists only on this machine"
        fi
        echo
    done

    echo "[toolchain]"
    echo "  rustc:  $(rustc --version 2>/dev/null || echo 'not installed')"
    echo "  cargo:  $(cargo --version 2>/dev/null || echo 'not installed')"
    [ -f "$HOME/repos/walker/rust-toolchain.toml" ] && \
        echo "  walker rust-toolchain.toml channel: $(grep -oP 'channel\s*=\s*"\K[^"]+' "$HOME/repos/walker/rust-toolchain.toml")"
    echo

    echo "[installed artifacts]"
    for b in walker mpvpaper hyprlock; do
        p=$(command -v "$b" 2>/dev/null || true)
        if [ -n "$p" ]; then
            owner=$(pacman -Qo "$p" 2>/dev/null | sed 's/.* is owned by //' || true)
            printf '  %-9s %s%s\n' "$b" "$p" "${owner:+  [pkg: $owner]}"
            [ -L "$p" ] && printf '  %-9s   -> %s\n' "" "$(readlink -f "$p")"
        fi
    done
} > "$OUT"

echo "wrote ${OUT/#$HOME/~}"
